name: HF Diagnostics

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install Node deps
        run: npm ci
      - name: Start mock server
        run: node tools/diag-hf/mock_hf_server.js & sleep 1
      - name: Run Jest
        run: npm test -- --runTestsByPath tests/hf/postWithRetry.test.ts || true
